### ISSUE TITLE
Huge error when player takes damage.

### ISSUE THREAD

**Issue by Nesseley** [MagicCheese1/Damage-Indicator#2]
https://pastebin.com/a3uGekhH

This server is running Paper version git-Paper-744 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
DamageIndicator ver 1.14

**Comment by MagicCheese1** [comment]
This seems to be an issue with java 16 and protocollib. What version of protocollib are you using?

**Comment by MagicCheese1** [comment]
This is an issue on protocollibs side. It works fine when using the protocollib dev builds. You might need to use those for java 16+

**Comment by Nesseley** [comment]
Thank you! Upgrading ProtocolLib fixed the issue :) Thanks again for a quick and friendly answer. Nice plugin!
