### ISSUE TITLE
Incompatibility with 1.20.4

### ISSUE THREAD

**Issue by Mikkel136** [MagicCheese1/Damage-Indicator#24]
This plugin unfortunately doesn't run on Spigot/Paper versions newer than 1.20.2

With very limited knowledge, I failed getting it to work with by re-compiling the 1.20 branch and adding a new packetManager instance locally.

You might also want to look into a newer version of Gradle ✌

**Comment by MagicCheese1** [comment]
Huge thanks for reporting this issue and the amazing pre-work.
